import type { Metadata } from "next";
import Script from "next/script";
import AdSense from "@/components/AdSense";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "google-adsense-account": "ca-pub-2248445708639121",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isProduction = process.env.NODE_ENV === "production";

  return (
    <html lang="en">
      <head>
        {isProduction && (
          <Script
            async
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2248445708639121"
            crossOrigin="anonymous"
            strategy="afterInteractive"
          />
        )}
      </head>
      <body className="antialiased">
        {isProduction && (
          <div className="w-full" style={{ minHeight: "100px" }}>
            <AdSense
              style={{ display: "block" }}
              format="auto"
              responsive={true}
              className="w-full"
            />
          </div>
        )}
        {children}
        {isProduction && (
          <div className="w-full" style={{ minHeight: "100px" }}>
            <AdSense
              style={{ display: "block" }}
              format="auto"
              responsive={true}
              className="w-full"
            />
          </div>
        )}
      </body>
    </html>
  );
}
